version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
#    command: mysqld --innodb-buffer-pool-size=256M
    volumes:
      - ./database:/var/lib/mysql
  web:
    tty: yes
    build: .
    volumes:
      - ../web_codes:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
