version: '3'

services:
  db:
    image: postgres
    volumes:
      - ../pg-data:/var/lib/postgresql/data
  web:
    tty: yes
    build: .
    volumes:
      - ../web_codes:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
#    command: python manage.py runserver 0.0.0.0:8000
